// AUTO-GENERATED by henry-whisper-macros — do not edit manually.
// Regenerate: run `cargo run` (debug) from src-tauri.

use henry_whisper_shared::AppSettings;

pub async fn frontend_trace(message: &str) -> ::std::result::Result<(), ::wasm_bindgen::JsValue> {
    invoke("frontend_trace", ::serde_wasm_bindgen::to_value(&::serde_json::json!({ "message": message }))
        .map_err(|e| ::wasm_bindgen::JsValue::from_str(&e.to_string()))?).await?;
    Ok(())
}

pub async fn frontend_debug(message: &str) -> ::std::result::Result<(), ::wasm_bindgen::JsValue> {
    invoke("frontend_debug", ::serde_wasm_bindgen::to_value(&::serde_json::json!({ "message": message }))
        .map_err(|e| ::wasm_bindgen::JsValue::from_str(&e.to_string()))?).await?;
    Ok(())
}

pub async fn frontend_info(message: &str) -> ::std::result::Result<(), ::wasm_bindgen::JsValue> {
    invoke("frontend_info", ::serde_wasm_bindgen::to_value(&::serde_json::json!({ "message": message }))
        .map_err(|e| ::wasm_bindgen::JsValue::from_str(&e.to_string()))?).await?;
    Ok(())
}

pub async fn frontend_warn(message: &str) -> ::std::result::Result<(), ::wasm_bindgen::JsValue> {
    invoke("frontend_warn", ::serde_wasm_bindgen::to_value(&::serde_json::json!({ "message": message }))
        .map_err(|e| ::wasm_bindgen::JsValue::from_str(&e.to_string()))?).await?;
    Ok(())
}

pub async fn frontend_error(message: &str) -> ::std::result::Result<(), ::wasm_bindgen::JsValue> {
    invoke("frontend_error", ::serde_wasm_bindgen::to_value(&::serde_json::json!({ "message": message }))
        .map_err(|e| ::wasm_bindgen::JsValue::from_str(&e.to_string()))?).await?;
    Ok(())
}

pub async fn get_settings() -> ::std::result::Result<AppSettings, ::wasm_bindgen::JsValue> {
    let __r = invoke("get_settings", ::wasm_bindgen::JsValue::NULL).await?;
    ::serde_wasm_bindgen::from_value(__r)
        .map_err(|e| ::wasm_bindgen::JsValue::from_str(&e.to_string()))
}

pub async fn save_settings(settings: AppSettings) -> ::std::result::Result<(), ::wasm_bindgen::JsValue> {
    invoke("save_settings", ::serde_wasm_bindgen::to_value(&::serde_json::json!({ "settings": settings }))
        .map_err(|e| ::wasm_bindgen::JsValue::from_str(&e.to_string()))?).await?;
    Ok(())
}

pub async fn hide_settings_window() -> ::std::result::Result<(), ::wasm_bindgen::JsValue> {
    invoke("hide_settings_window", ::wasm_bindgen::JsValue::NULL).await?;
    Ok(())
}
