/// Metadata about a single Tauri IPC command, captured by `#[ipc_command]`.
pub struct CommandMeta {
    pub name: &'static str,
    /// Non-Tauri parameters as `(param_name, type_str)` pairs.
    pub params: &'static [(&'static str, &'static str)],
    /// `None` means the binding returns `()`. `Some(t)` means it deserializes to `t`.
    pub return_type: Option<&'static str>,
}

pub struct IpcBuilder {
    header: String,
    commands: Vec<CommandMeta>,
}

impl Default for IpcBuilder {
    fn default() -> Self {
        Self::new()
    }
}

impl IpcBuilder {
    pub fn new() -> Self {
        Self {
            header: String::new(),
            commands: Vec::new(),
        }
    }

    /// Lines prepended after the auto-generated banner (e.g. `use` statements).
    pub fn header(mut self, h: impl Into<String>) -> Self {
        self.header = h.into();
        self
    }

    pub fn commands(mut self, cmds: Vec<CommandMeta>) -> Self {
        self.commands = cmds;
        self
    }

    /// Render and write the frontend IPC bindings to `path`.
    pub fn export(self, path: &str) -> std::io::Result<()> {
        std::fs::write(path, self.render())
    }

    fn render(&self) -> String {
        let mut out = String::new();
        out.push_str("// AUTO-GENERATED by henry-whisper-macros — do not edit manually.\n");
        out.push_str("// Regenerate: run `cargo run` (debug) from src-tauri.\n");
        if !self.header.is_empty() {
            out.push('\n');
            out.push_str(&self.header);
            out.push('\n');
        }
        for cmd in &self.commands {
            out.push('\n');
            out.push_str(&render_fn(cmd));
        }
        out
    }
}

fn render_fn(cmd: &CommandMeta) -> String {
    let name = cmd.name;

    let sig_params: Vec<String> = cmd
        .params
        .iter()
        .map(|(n, t)| {
            let t = if *t == "String" { "&str" } else { t };
            format!("{n}: {t}")
        })
        .collect();

    let args_expr = if cmd.params.is_empty() {
        "::wasm_bindgen::JsValue::NULL".to_string()
    } else {
        let fields: String = cmd
            .params
            .iter()
            .map(|(n, _)| format!("\"{n}\": {n}"))
            .collect::<Vec<_>>()
            .join(", ");
        format!(
            "::serde_wasm_bindgen::to_value(&::serde_json::json!({{ {fields} }}))\n        \
             .map_err(|e| ::wasm_bindgen::JsValue::from_str(&e.to_string()))?"
        )
    };

    let sig = sig_params.join(", ");

    match cmd.return_type {
        None => format!(
            "pub async fn {name}({sig}) \
             -> ::std::result::Result<(), ::wasm_bindgen::JsValue> {{\n    \
                 invoke(\"{name}\", {args_expr}).await?;\n    \
                 Ok(())\n\
             }}\n"
        ),
        Some(ty) => format!(
            "pub async fn {name}({sig}) \
             -> ::std::result::Result<{ty}, ::wasm_bindgen::JsValue> {{\n    \
                 let __r = invoke(\"{name}\", {args_expr}).await?;\n    \
                 ::serde_wasm_bindgen::from_value(__r)\n        \
                     .map_err(|e| ::wasm_bindgen::JsValue::from_str(&e.to_string()))\n\
             }}\n"
        ),
    }
}
